[package]
name = "eth_trie"
version = "0.1.0"
authors = ["Jason Carver <ut96caarrs@snkmail.com>"]
description = "Ethereum-compatible Merkle-Patricia Trie."
license = "Apache-2.0"
edition = "2018"
readme = "README.md"
keywords = ["patricia", "mpt", "evm", "trie", "ethereum"]
repository = "https://github.com/carver/eth-trie.rs"
homepage = "https://github.com/carver/eth-trie.rs"
documentation = "https://docs.rs/eth_trie"

[dependencies]
sp-std = { version = "4.0.0", default-features = false }
keccak-hash = { version = "0.9", default-features = false }
rlp = { version = "0.5.1", default-features = false }

[dev-dependencies]
rand = "0.8.3"
hex = "0.4.2"
criterion = "0.3.5"
ethereum-types = "0.13.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[[bench]]
name = "trie"
harness = false
